[general]

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]

TERM = "xterm-256color"

[window]

opacity = 0.4
blur = true
decorations = "buttonless"

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16.0

[cursor]

style = { shape = "Block", blinking = "On" }
