[general]

import = [
  "~/.config/alacritty/current-theme.toml",
  "~/.config/alacritty/decoration.toml",
]


[env]

TERM = "xterm-256color"
# TERM = "alacritty"

[terminal]

shell = { program = "zsh", args = ["-l"] }

[window]

opacity = 0.9
blur = true

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16.0

[cursor]

style = { shape = "Block", blinking = "On" }
