[general]

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/eink.toml",
  "~/.config/alacritty/decoration.toml",
]


[env]

TERM = "xterm-256color"
# TERM = "alacritty"

[terminal]

shell = { program = "zsh", args = ["-l"] }

[window]

opacity = 0.9
blur = true

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16.0

[cursor]

style = { shape = "Block", blinking = "On" }
