# vim:ft=kitty
## upstream: https://github.com/alexxGmZ/e-ink.kitty/blob/main/E-Ink.conf

foreground #58534C
background #E0DBD3
selection_foreground none
selection_background #C8C3BB

cursor none

# black
color0  #E0DBD3
color8  #615C56

# red / error
color1  #C4607A
color9  #C4607A

# green / success
color2  #8BAD79
color10 #8BAD79

# yellow / warning
color3  #B89868
color11 #B89868

# blue / primary accent
color4  #6B9AB8
color12 #6B9AB8

# magenta / secondary accent
color5  #58534C
color13 #58534C

# cyan
color6  #4E4A45
color14 #4E4A45

# white
color7  #615C56
color15 #7A756E
