add_newline = false
format = """$directory$character"""
palette = "midori"
right_format = """$all"""
command_timeout = 1000

[directory]
style = "bold secondary"

[character]
success_symbol = "[❯](primary)"
error_symbol   = "[❯](error)"

[git_branch]
style  = "success"
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style      = "success"
staged     = "[+](success)"
modified   = "[!](warning)"
deleted    = "[-](error)"
conflicted = "[~](error)"
untracked  = "[?](subtle)"

[cmd_duration]
style = "warning"

[palettes.midori]
red    = "#C4607A"
green  = "#8BAD79"
yellow = "#B89868"
blue   = "#6B9AB8"
purple = "#58534C"
cyan   = "#4E4A45"
primary   = "#6B9AB8"
secondary = "#58534C"
success   = "#8BAD79"
warning   = "#B89868"
error     = "#C4607A"
subtle    = "#857F78"

[palettes.eink]
red    = "#C4607A"
green  = "#8BAD79"
yellow = "#B89868"
blue   = "#6B9AB8"
purple = "#474747"
cyan   = "#4A4A4A"
primary   = "#6B9AB8"
secondary = "#474747"
success   = "#8BAD79"
warning   = "#B89868"
error     = "#C4607A"
subtle    = "#868686"
