set -g pane-active-border-style   'fg=#6B9AB8,bg=default'
set -g pane-border-style          'fg=#5E5E5E,bg=default'
set -g status-style               'bg=default,fg=#857F78'
set -g window-status-current-style 'fg=#6B9AB8,bold'
set -g window-status-style        'fg=#857F78'
