set -g pane-active-border-style    'fg=#3C3C3C,bg=default'
set -g pane-border-style           'fg=#AAAAAA,bg=default'
set -g status-style                'bg=default,fg=#AAAAAA'
set -g window-status-current-style 'fg=#3C3C3C,bold'
set -g window-status-style         'fg=#AAAAAA'
