vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "eink"
vim.opt.background = "light"

local c = {
  bg       = "#F2EDE8",
  bg_float = "#ECE8E2",
  bg_alt   = "#E5E1DA",
  faint    = "#D4D0CA",
  ink5     = "#B8B4AE",
  ink4     = "#9C9892",
  ink3     = "#7A7672",
  ink2     = "#5A5652",
  ink1     = "#3E3B36",
  ink0     = "#2C2926",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hi("Normal",          { fg = c.ink0,  bg = c.bg })
hi("NormalFloat",     { fg = c.ink0,  bg = c.bg_float })
hi("FloatBorder",     { fg = c.ink4,  bg = c.bg_float })
hi("Visual",          { fg = c.ink0,  bg = c.bg_alt })
hi("Search",          { fg = c.bg,    bg = c.ink1 })
hi("IncSearch",       { fg = c.bg,    bg = c.ink0, bold = true })
hi("CurSearch",       { fg = c.bg,    bg = c.ink0, bold = true })
hi("CursorLine",      { bg = c.bg_alt })
hi("CursorLineNr",    { fg = c.ink1,  bold = true })
hi("LineNr",          { fg = c.ink4 })
hi("SignColumn",      { bg = c.bg })
hi("ColorColumn",     { bg = c.bg_alt })
hi("StatusLine",      { fg = c.ink0,  bg = c.faint })
hi("StatusLineNC",    { fg = c.ink4,  bg = c.faint })
hi("WinSeparator",    { fg = c.faint })
hi("VertSplit",       { fg = c.faint })
hi("Pmenu",           { fg = c.ink0,  bg = c.bg_float })
hi("PmenuSel",        { fg = c.ink0,  bg = c.faint, bold = true })
hi("PmenuSbar",       { bg = c.faint })
hi("PmenuThumb",      { bg = c.ink4 })
hi("TabLine",         { fg = c.ink4,  bg = c.faint })
hi("TabLineSel",      { fg = c.ink0,  bg = c.bg, bold = true })
hi("TabLineFill",     { bg = c.faint })
hi("MatchParen",      { fg = c.ink0,  bold = true, underline = true })
hi("Folded",          { fg = c.ink4,  bg = c.bg_alt })
hi("FoldColumn",      { fg = c.ink4,  bg = c.bg })
hi("Title",           { fg = c.ink1,  bold = true })
hi("NonText",         { fg = c.faint })
hi("EndOfBuffer",     { fg = c.faint })
hi("Whitespace",      { fg = c.faint })
hi("SpecialKey",      { fg = c.faint })
hi("WildMenu",        { fg = c.bg,    bg = c.ink0, bold = true })
hi("QuickFixLine",    { bg = c.bg_alt })
hi("Directory",       { fg = c.ink1,  bold = true })
hi("Question",        { fg = c.ink2 })
hi("MoreMsg",         { fg = c.ink2 })
hi("ModeMsg",         { fg = c.ink0,  bold = true })
hi("ErrorMsg",        { fg = c.ink0,  bold = true, underline = true })
hi("WarningMsg",      { fg = c.ink3 })
hi("Todo",            { fg = c.ink1,  bold = true })

hi("Comment",         { fg = c.ink5,  italic = true })
hi("Keyword",         { fg = c.ink1,  bold = true })
hi("Statement",       { fg = c.ink1,  bold = true })
hi("Conditional",     { fg = c.ink1,  bold = true })
hi("Repeat",          { fg = c.ink1,  bold = true })
hi("Label",           { fg = c.ink1,  bold = true })
hi("Exception",       { fg = c.ink1,  bold = true })
hi("Operator",        { fg = c.ink4 })
hi("Function",        { fg = c.ink0,  bold = true })
hi("Identifier",      { fg = c.ink0 })
hi("String",          { fg = c.ink2 })
hi("Character",       { fg = c.ink2 })
hi("Number",          { fg = c.ink3 })
hi("Float",           { fg = c.ink3 })
hi("Boolean",         { fg = c.ink1,  bold = true })
hi("Constant",        { fg = c.ink3 })
hi("Type",            { fg = c.ink1,  bold = true })
hi("StorageClass",    { fg = c.ink1,  bold = true })
hi("Structure",       { fg = c.ink1,  bold = true })
hi("Typedef",         { fg = c.ink1,  bold = true })
hi("PreProc",         { fg = c.ink3 })
hi("Include",         { fg = c.ink3 })
hi("Define",          { fg = c.ink3 })
hi("Macro",           { fg = c.ink3 })
hi("Special",         { fg = c.ink4 })
hi("SpecialChar",     { fg = c.ink4 })
hi("Delimiter",       { fg = c.ink4 })
hi("SpecialComment",  { fg = c.ink5,  italic = true })
hi("Underlined",      { underline = true })
hi("Error",           { fg = c.ink0,  bold = true, underline = true })

hi("@comment",               { fg = c.ink5,  italic = true })
hi("@keyword",               { fg = c.ink1,  bold = true })
hi("@keyword.return",        { fg = c.ink1,  bold = true })
hi("@keyword.function",      { fg = c.ink1,  bold = true })
hi("@keyword.operator",      { fg = c.ink4 })
hi("@keyword.import",        { fg = c.ink3 })
hi("@conditional",           { fg = c.ink1,  bold = true })
hi("@repeat",                { fg = c.ink1,  bold = true })
hi("@exception",             { fg = c.ink1,  bold = true })
hi("@function",              { fg = c.ink0,  bold = true })
hi("@function.call",         { fg = c.ink0 })
hi("@function.builtin",      { fg = c.ink1,  bold = true })
hi("@method",                { fg = c.ink0,  bold = true })
hi("@method.call",           { fg = c.ink0 })
hi("@constructor",           { fg = c.ink1,  bold = true })
hi("@string",                { fg = c.ink2 })
hi("@string.escape",         { fg = c.ink3 })
hi("@string.special",        { fg = c.ink3 })
hi("@character",             { fg = c.ink2 })
hi("@number",                { fg = c.ink3 })
hi("@float",                 { fg = c.ink3 })
hi("@boolean",               { fg = c.ink1,  bold = true })
hi("@constant",              { fg = c.ink3 })
hi("@constant.builtin",      { fg = c.ink1,  bold = true })
hi("@constant.macro",        { fg = c.ink3 })
hi("@type",                  { fg = c.ink1,  bold = true })
hi("@type.builtin",          { fg = c.ink1,  bold = true })
hi("@type.definition",       { fg = c.ink1,  bold = true })
hi("@storageclass",          { fg = c.ink1,  bold = true })
hi("@namespace",             { fg = c.ink0 })
hi("@variable",              { fg = c.ink0 })
hi("@variable.builtin",      { fg = c.ink1,  bold = true })
hi("@parameter",             { fg = c.ink0 })
hi("@field",                 { fg = c.ink0 })
hi("@property",              { fg = c.ink0 })
hi("@operator",              { fg = c.ink4 })
hi("@punctuation.delimiter", { fg = c.ink4 })
hi("@punctuation.bracket",   { fg = c.ink4 })
hi("@punctuation.special",   { fg = c.ink3 })
hi("@preproc",               { fg = c.ink3 })
hi("@tag",                   { fg = c.ink1,  bold = true })
hi("@tag.attribute",         { fg = c.ink2,  italic = true })
hi("@tag.delimiter",         { fg = c.ink4 })
hi("@text.title",            { fg = c.ink1,  bold = true })
hi("@text.strong",           { bold = true })
hi("@text.emphasis",         { italic = true })
hi("@text.uri",              { fg = c.ink2,  underline = true })
hi("@text.reference",        { fg = c.ink2 })
hi("@text.todo",             { fg = c.ink1,  bold = true })
hi("@text.note",             { fg = c.ink3 })
hi("@text.warning",          { fg = c.ink3 })
hi("@text.danger",           { fg = c.ink0,  bold = true, underline = true })

hi("DiagnosticError",            { fg = c.ink0 })
hi("DiagnosticWarn",             { fg = c.ink3 })
hi("DiagnosticInfo",             { fg = c.ink4 })
hi("DiagnosticHint",             { fg = c.ink5 })
hi("DiagnosticUnderlineError",   { sp = c.ink0,  undercurl = true })
hi("DiagnosticUnderlineWarn",    { sp = c.ink3,  undercurl = true })
hi("DiagnosticUnderlineInfo",    { sp = c.ink4,  undercurl = true })
hi("DiagnosticUnderlineHint",    { sp = c.ink5,  undercurl = true })

hi("GitSignsAdd",       { fg = c.ink2 })
hi("GitSignsChange",    { fg = c.ink3 })
hi("GitSignsDelete",    { fg = c.ink0,  bold = true })
hi("GitSignsAddNr",     { fg = c.ink2 })
hi("GitSignsChangeNr",  { fg = c.ink3 })
hi("GitSignsDeleteNr",  { fg = c.ink0 })
hi("MiniDiffSignAdd",     { fg = c.ink2 })
hi("MiniDiffSignChange",  { fg = c.ink3 })
hi("MiniDiffSignDelete",  { fg = c.ink0,  bold = true })
hi("MiniDiffOverAdd",     { fg = c.ink2 })
hi("MiniDiffOverChange",  { fg = c.ink3 })
hi("MiniDiffOverDelete",  { fg = c.ink0 })
hi("NeoTreeGitAdded",     { fg = c.ink2 })
hi("NeoTreeGitModified",  { fg = c.ink3 })
hi("NeoTreeGitDeleted",   { fg = c.ink0,  bold = true })
hi("NeoTreeGitStaged",    { fg = c.ink2 })
hi("NeoTreeGitUnstaged",  { fg = c.ink3 })
hi("NeoTreeGitUntracked", { fg = c.ink4 })
hi("NeoTreeGitIgnored",   { fg = c.ink5 })
hi("NeoTreeGitConflict",  { fg = c.ink0,  bold = true, underline = true })
hi("DiffAdd",    { fg = c.ink2 })
hi("DiffChange", { fg = c.ink3 })
hi("DiffDelete", { fg = c.ink0,  bold = true })
hi("DiffText",   { fg = c.ink0,  underline = true })
