vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "serika"
vim.opt.background = "light"

-- Serika: yellow (#E2B714) is the UI accent only — too low contrast for syntax on light bg.
-- Syntax uses dark fg + bold/italic; strings faded (subtle); git signs use blue; errors use red.
local c = {
  bg      = "#E1E1E3",
  fg      = "#323437",
  subtle  = "#AAAEB3",
  faint   = "#D1D3D8",
  mid     = "#4A4D52",
  accent  = "#E2B714",
  blue    = "#6B9AB8",
  error   = "#DA3333",
  warn    = "#C08030",
  bg_alt  = "#D1D3D8",
  bg_float = "#EAEAEC",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Base UI — yellow as accent for interactive elements only
hi("Normal",          { fg = c.fg,     bg = c.bg })
hi("NormalFloat",     { fg = c.fg,     bg = c.bg_float })
hi("FloatBorder",     { fg = c.subtle, bg = c.bg_float })
hi("Visual",          { fg = c.fg,     bg = c.faint })
hi("Search",          { fg = c.fg,     bg = c.accent })
hi("IncSearch",       { fg = c.fg,     bg = c.accent, bold = true })
hi("CurSearch",       { fg = c.fg,     bg = c.accent, bold = true })
hi("CursorLine",      { bg = c.bg_alt })
hi("CursorLineNr",    { fg = c.accent, bold = true })
hi("LineNr",          { fg = c.subtle })
hi("SignColumn",      { bg = c.bg })
hi("ColorColumn",     { bg = c.bg_alt })
hi("StatusLine",      { fg = c.fg,     bg = c.faint })
hi("StatusLineNC",    { fg = c.subtle, bg = c.faint })
hi("WinSeparator",    { fg = c.faint })
hi("VertSplit",       { fg = c.faint })
hi("Pmenu",           { fg = c.fg,     bg = c.bg_float })
hi("PmenuSel",        { fg = c.fg,     bg = c.faint, bold = true })
hi("PmenuSbar",       { bg = c.faint })
hi("PmenuThumb",      { bg = c.subtle })
hi("TabLine",         { fg = c.subtle, bg = c.faint })
hi("TabLineSel",      { fg = c.fg,     bg = c.bg, bold = true })
hi("TabLineFill",     { bg = c.faint })
hi("MatchParen",      { fg = c.fg,     bg = c.accent, bold = true })
hi("Folded",          { fg = c.subtle, bg = c.bg_alt })
hi("FoldColumn",      { fg = c.subtle, bg = c.bg })
hi("Title",           { fg = c.fg, bold = true })
hi("NonText",         { fg = c.faint })
hi("EndOfBuffer",     { fg = c.faint })
hi("Whitespace",      { fg = c.faint })
hi("SpecialKey",      { fg = c.faint })
hi("WildMenu",        { fg = c.fg, bg = c.accent, bold = true })
hi("QuickFixLine",    { bg = c.faint })
hi("Directory",       { fg = c.fg, bold = true })
hi("Question",        { fg = c.subtle })
hi("MoreMsg",         { fg = c.subtle })
hi("ModeMsg",         { fg = c.fg, bold = true })
hi("ErrorMsg",        { fg = c.error })
hi("WarningMsg",      { fg = c.warn })
hi("Todo",            { fg = c.warn, bold = true })

-- Syntax — no yellow in syntax (unreadable on light), bold/italic + subtle strings + blue git
hi("Comment",         { fg = c.subtle, italic = true })
hi("Keyword",         { fg = c.fg, bold = true })
hi("Statement",       { fg = c.fg, bold = true })
hi("Conditional",     { fg = c.fg, bold = true })
hi("Repeat",          { fg = c.fg, bold = true })
hi("Label",           { fg = c.fg, bold = true })
hi("Exception",       { fg = c.fg, bold = true })
hi("Operator",        { fg = c.fg })
hi("Function",        { fg = c.fg, bold = true })
hi("Identifier",      { fg = c.fg })
hi("String",          { fg = c.subtle })
hi("Character",       { fg = c.subtle })
hi("Number",          { fg = c.error })
hi("Float",           { fg = c.error })
hi("Boolean",         { fg = c.error })
hi("Constant",        { fg = c.warn })
hi("Type",            { fg = c.mid, bold = true })
hi("StorageClass",    { fg = c.mid, bold = true })
hi("Structure",       { fg = c.mid, bold = true })
hi("Typedef",         { fg = c.mid, bold = true })
hi("PreProc",         { fg = c.fg })
hi("Include",         { fg = c.fg })
hi("Define",          { fg = c.fg })
hi("Macro",           { fg = c.fg })
hi("Special",         { fg = c.subtle })
hi("SpecialChar",     { fg = c.subtle })
hi("Delimiter",       { fg = c.subtle })
hi("SpecialComment",  { fg = c.subtle, italic = true })
hi("Underlined",      { underline = true })
hi("Error",           { fg = c.error })

-- Treesitter
hi("@comment",              { fg = c.subtle, italic = true })
hi("@keyword",              { fg = c.fg, bold = true })
hi("@keyword.return",       { fg = c.fg, bold = true })
hi("@keyword.function",     { fg = c.fg, bold = true })
hi("@keyword.operator",     { fg = c.fg, bold = true })
hi("@keyword.import",       { fg = c.fg })
hi("@conditional",          { fg = c.fg, bold = true })
hi("@repeat",               { fg = c.fg, bold = true })
hi("@exception",            { fg = c.fg, bold = true })
hi("@function",             { fg = c.fg, bold = true })
hi("@function.call",        { fg = c.fg })
hi("@function.builtin",     { fg = c.fg, bold = true })
hi("@method",               { fg = c.fg, bold = true })
hi("@method.call",          { fg = c.fg })
hi("@constructor",          { fg = c.fg, bold = true })
hi("@string",               { fg = c.subtle })
hi("@string.escape",        { fg = c.subtle })
hi("@string.special",       { fg = c.subtle })
hi("@character",            { fg = c.subtle })
hi("@number",               { fg = c.error })
hi("@float",                { fg = c.error })
hi("@boolean",              { fg = c.error })
hi("@constant",             { fg = c.warn })
hi("@constant.builtin",     { fg = c.warn })
hi("@constant.macro",       { fg = c.warn })
hi("@type",                 { fg = c.mid, bold = true })
hi("@type.builtin",         { fg = c.mid, bold = true })
hi("@type.definition",      { fg = c.mid, bold = true })
hi("@storageclass",         { fg = c.mid, bold = true })
hi("@namespace",            { fg = c.fg })
hi("@variable",             { fg = c.fg })
hi("@variable.builtin",     { fg = c.mid })
hi("@parameter",            { fg = c.fg })
hi("@field",                { fg = c.fg })
hi("@property",             { fg = c.fg })
hi("@operator",             { fg = c.fg })
hi("@punctuation.delimiter",{ fg = c.subtle })
hi("@punctuation.bracket",  { fg = c.subtle })
hi("@punctuation.special",  { fg = c.subtle })
hi("@preproc",              { fg = c.fg })
hi("@tag",                  { fg = c.fg, bold = true })
hi("@tag.attribute",        { fg = c.warn, italic = true })
hi("@tag.delimiter",        { fg = c.subtle })
hi("@text.title",           { fg = c.fg, bold = true })
hi("@text.strong",          { bold = true })
hi("@text.emphasis",        { italic = true })
hi("@text.uri",             { fg = c.mid, underline = true })
hi("@text.reference",       { fg = c.mid })
hi("@text.todo",            { fg = c.warn, bold = true })
hi("@text.note",            { fg = c.fg })
hi("@text.warning",         { fg = c.warn })
hi("@text.danger",          { fg = c.error })

-- LSP diagnostics
hi("DiagnosticError",            { fg = c.error })
hi("DiagnosticWarn",             { fg = c.warn })
hi("DiagnosticInfo",             { fg = c.mid })
hi("DiagnosticHint",             { fg = c.subtle })
hi("DiagnosticUnderlineError",   { sp = c.error, undercurl = true })
hi("DiagnosticUnderlineWarn",    { sp = c.warn,  undercurl = true })
hi("DiagnosticUnderlineInfo",    { sp = c.mid,   undercurl = true })
hi("DiagnosticUnderlineHint",    { sp = c.subtle, undercurl = true })

-- Git signs
hi("GitSignsAdd",       { fg = c.blue })
hi("GitSignsChange",    { fg = c.blue })
hi("GitSignsDelete",    { fg = c.error })
hi("GitSignsAddNr",     { fg = c.blue })
hi("GitSignsChangeNr",  { fg = c.blue })
hi("GitSignsDeleteNr",  { fg = c.error })

hi("MiniDiffSignAdd",     { fg = c.blue })
hi("MiniDiffSignChange",  { fg = c.blue })
hi("MiniDiffSignDelete",  { fg = c.error })
hi("MiniDiffOverAdd",     { fg = c.blue })
hi("MiniDiffOverChange",  { fg = c.blue })
hi("MiniDiffOverDelete",  { fg = c.error })

hi("NeoTreeGitAdded",     { fg = c.blue })
hi("NeoTreeGitModified",  { fg = c.blue })
hi("NeoTreeGitDeleted",   { fg = c.error })
hi("NeoTreeGitStaged",    { fg = c.blue })
hi("NeoTreeGitUnstaged",  { fg = c.warn })
hi("NeoTreeGitUntracked", { fg = c.subtle })
hi("NeoTreeGitIgnored",   { fg = c.subtle })
hi("NeoTreeGitConflict",  { fg = c.error })

hi("DiffAdd",    { fg = c.blue })
hi("DiffChange", { fg = c.blue })
hi("DiffDelete", { fg = c.error })
hi("DiffText",   { fg = c.warn })
