vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "serika-dark"
vim.opt.background = "dark"

-- Serika Dark: yellow (#E2B714) is the primary accent — excellent contrast on dark bg (~8:1).
-- Keywords/functions use yellow. Strings use green. Errors use red.
local c = {
  bg      = "#323437",
  fg      = "#D1D0C5",
  subtle  = "#646669",
  faint   = "#2C2E31",
  mid     = "#4A4D52",
  light   = "#8A8E93",
  accent  = "#E2B714",
  green   = "#8AA858",
  error   = "#CA4754",
  warn    = "#D4A332",
  bg_alt  = "#2C2E31",
  bg_float = "#3A3D40",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Base UI
hi("Normal",          { fg = c.fg,     bg = c.bg })
hi("NormalFloat",     { fg = c.fg,     bg = c.bg_float })
hi("FloatBorder",     { fg = c.subtle, bg = c.bg_float })
hi("Visual",          { fg = c.fg,     bg = c.mid })
hi("Search",          { fg = c.faint,  bg = c.accent })
hi("IncSearch",       { fg = c.faint,  bg = c.accent, bold = true })
hi("CurSearch",       { fg = c.faint,  bg = c.accent, bold = true })
hi("CursorLine",      { bg = c.bg_alt })
hi("CursorLineNr",    { fg = c.accent, bold = true })
hi("LineNr",          { fg = c.subtle })
hi("SignColumn",      { bg = c.bg })
hi("ColorColumn",     { bg = c.bg_alt })
hi("StatusLine",      { fg = c.fg,     bg = c.faint })
hi("StatusLineNC",    { fg = c.subtle, bg = c.faint })
hi("WinSeparator",    { fg = c.faint })
hi("VertSplit",       { fg = c.faint })
hi("Pmenu",           { fg = c.fg,     bg = c.bg_float })
hi("PmenuSel",        { fg = c.fg,     bg = c.mid, bold = true })
hi("PmenuSbar",       { bg = c.mid })
hi("PmenuThumb",      { bg = c.subtle })
hi("TabLine",         { fg = c.subtle, bg = c.faint })
hi("TabLineSel",      { fg = c.fg,     bg = c.bg, bold = true })
hi("TabLineFill",     { bg = c.faint })
hi("MatchParen",      { fg = c.faint,  bg = c.accent, bold = true })
hi("Folded",          { fg = c.subtle, bg = c.bg_alt })
hi("FoldColumn",      { fg = c.subtle, bg = c.bg })
hi("Title",           { fg = c.accent, bold = true })
hi("NonText",         { fg = c.subtle })
hi("EndOfBuffer",     { fg = c.subtle })
hi("Whitespace",      { fg = c.mid })
hi("SpecialKey",      { fg = c.subtle })
hi("WildMenu",        { fg = c.faint,  bg = c.accent, bold = true })
hi("QuickFixLine",    { bg = c.mid })
hi("Directory",       { fg = c.accent })
hi("Question",        { fg = c.green })
hi("MoreMsg",         { fg = c.green })
hi("ModeMsg",         { fg = c.fg, bold = true })
hi("ErrorMsg",        { fg = c.error })
hi("WarningMsg",      { fg = c.warn })
hi("Todo",            { fg = c.warn, bold = true })

-- Syntax — yellow for keywords/functions (great contrast on dark), green for strings
hi("Comment",         { fg = c.subtle, italic = true })
hi("Keyword",         { fg = c.accent, bold = true })
hi("Statement",       { fg = c.accent, bold = true })
hi("Conditional",     { fg = c.accent, bold = true })
hi("Repeat",          { fg = c.accent, bold = true })
hi("Label",           { fg = c.accent, bold = true })
hi("Exception",       { fg = c.accent, bold = true })
hi("Operator",        { fg = c.fg })
hi("Function",        { fg = c.accent, bold = true })
hi("Identifier",      { fg = c.fg })
hi("String",          { fg = c.green })
hi("Character",       { fg = c.green })
hi("Number",          { fg = c.error })
hi("Float",           { fg = c.error })
hi("Boolean",         { fg = c.error })
hi("Constant",        { fg = c.warn })
hi("Type",            { fg = c.light, bold = true })
hi("StorageClass",    { fg = c.light, bold = true })
hi("Structure",       { fg = c.light, bold = true })
hi("Typedef",         { fg = c.light, bold = true })
hi("PreProc",         { fg = c.fg })
hi("Include",         { fg = c.fg })
hi("Define",          { fg = c.fg })
hi("Macro",           { fg = c.fg })
hi("Special",         { fg = c.subtle })
hi("SpecialChar",     { fg = c.subtle })
hi("Delimiter",       { fg = c.subtle })
hi("SpecialComment",  { fg = c.subtle, italic = true })
hi("Underlined",      { underline = true })
hi("Error",           { fg = c.error })

-- Treesitter
hi("@comment",              { fg = c.subtle, italic = true })
hi("@keyword",              { fg = c.accent, bold = true })
hi("@keyword.return",       { fg = c.accent, bold = true })
hi("@keyword.function",     { fg = c.accent, bold = true })
hi("@keyword.operator",     { fg = c.accent, bold = true })
hi("@keyword.import",       { fg = c.fg })
hi("@conditional",          { fg = c.accent, bold = true })
hi("@repeat",               { fg = c.accent, bold = true })
hi("@exception",            { fg = c.accent, bold = true })
hi("@function",             { fg = c.accent, bold = true })
hi("@function.call",        { fg = c.fg })
hi("@function.builtin",     { fg = c.accent })
hi("@method",               { fg = c.accent, bold = true })
hi("@method.call",          { fg = c.fg })
hi("@constructor",          { fg = c.fg, bold = true })
hi("@string",               { fg = c.green })
hi("@string.escape",        { fg = c.subtle })
hi("@string.special",       { fg = c.subtle })
hi("@character",            { fg = c.green })
hi("@number",               { fg = c.error })
hi("@float",                { fg = c.error })
hi("@boolean",              { fg = c.error })
hi("@constant",             { fg = c.warn })
hi("@constant.builtin",     { fg = c.warn })
hi("@constant.macro",       { fg = c.warn })
hi("@type",                 { fg = c.light, bold = true })
hi("@type.builtin",         { fg = c.light, bold = true })
hi("@type.definition",      { fg = c.light, bold = true })
hi("@storageclass",         { fg = c.light, bold = true })
hi("@namespace",            { fg = c.fg })
hi("@variable",             { fg = c.fg })
hi("@variable.builtin",     { fg = c.light })
hi("@parameter",            { fg = c.fg })
hi("@field",                { fg = c.fg })
hi("@property",             { fg = c.fg })
hi("@operator",             { fg = c.fg })
hi("@punctuation.delimiter",{ fg = c.subtle })
hi("@punctuation.bracket",  { fg = c.subtle })
hi("@punctuation.special",  { fg = c.subtle })
hi("@preproc",              { fg = c.fg })
hi("@tag",                  { fg = c.accent, bold = true })
hi("@tag.attribute",        { fg = c.warn, italic = true })
hi("@tag.delimiter",        { fg = c.subtle })
hi("@text.title",           { fg = c.accent, bold = true })
hi("@text.strong",          { bold = true })
hi("@text.emphasis",        { italic = true })
hi("@text.uri",             { fg = c.accent, underline = true })
hi("@text.reference",       { fg = c.accent })
hi("@text.todo",            { fg = c.warn, bold = true })
hi("@text.note",            { fg = c.accent })
hi("@text.warning",         { fg = c.warn })
hi("@text.danger",          { fg = c.error })

-- LSP diagnostics
hi("DiagnosticError",            { fg = c.error })
hi("DiagnosticWarn",             { fg = c.warn })
hi("DiagnosticInfo",             { fg = c.accent })
hi("DiagnosticHint",             { fg = c.subtle })
hi("DiagnosticUnderlineError",   { sp = c.error,  undercurl = true })
hi("DiagnosticUnderlineWarn",    { sp = c.warn,   undercurl = true })
hi("DiagnosticUnderlineInfo",    { sp = c.accent, undercurl = true })
hi("DiagnosticUnderlineHint",    { sp = c.subtle, undercurl = true })

-- Git signs
hi("GitSignsAdd",       { fg = c.green })
hi("GitSignsChange",    { fg = c.accent })
hi("GitSignsDelete",    { fg = c.error })
hi("GitSignsAddNr",     { fg = c.green })
hi("GitSignsChangeNr",  { fg = c.accent })
hi("GitSignsDeleteNr",  { fg = c.error })

hi("MiniDiffSignAdd",     { fg = c.green })
hi("MiniDiffSignChange",  { fg = c.accent })
hi("MiniDiffSignDelete",  { fg = c.error })
hi("MiniDiffOverAdd",     { fg = c.green })
hi("MiniDiffOverChange",  { fg = c.accent })
hi("MiniDiffOverDelete",  { fg = c.error })

hi("NeoTreeGitAdded",     { fg = c.green })
hi("NeoTreeGitModified",  { fg = c.accent })
hi("NeoTreeGitDeleted",   { fg = c.error })
hi("NeoTreeGitStaged",    { fg = c.green })
hi("NeoTreeGitUnstaged",  { fg = c.warn })
hi("NeoTreeGitUntracked", { fg = c.subtle })
hi("NeoTreeGitIgnored",   { fg = c.subtle })
hi("NeoTreeGitConflict",  { fg = c.error })

hi("DiffAdd",    { fg = c.green })
hi("DiffChange", { fg = c.accent })
hi("DiffDelete", { fg = c.error })
hi("DiffText",   { fg = c.warn })
