[colors.primary]
background = "#F2EDE8"
foreground = "#2C2926"

[colors.cursor]
cursor = "#3E3B36"
text   = "#2C2926"

[colors.selection]
background = "#E5E1DA"
text       = "#2C2926"

[colors.normal]
black   = "#F2EDE8"
red     = "#3E3B36"
green   = "#5A5652"
yellow  = "#7A7672"
blue    = "#504D49"
magenta = "#686461"
cyan    = "#9C9892"
white   = "#AFABA5"

[colors.bright]
black   = "#C8C4BE"
red     = "#3E3B36"
green   = "#686461"
yellow  = "#9C9892"
blue    = "#504D49"
magenta = "#7A7672"
cyan    = "#AFABA5"
white   = "#E5E1DA"
