[colors.primary]
background = "#E0DBD3"
foreground = "#58534C"

[colors.cursor]
cursor = "#6B9AB8"
text   = "#58534C"

[colors.selection]
background = "#D8D3CB"
text       = "#58534C"

[colors.normal]
black   = "#E0DBD3"
red     = "#C4607A"
green   = "#8BAD79"
yellow  = "#B89868"
blue    = "#6B9AB8"
magenta = "#58534C"
cyan    = "#4E4A45"
white   = "#615C56"

[colors.bright]
black   = "#615C56"
red     = "#C4607A"
green   = "#8BAD79"
yellow  = "#B89868"
blue    = "#6B9AB8"
magenta = "#58534C"
cyan    = "#4E4A45"
white   = "#7A756E"
