[colors.primary]
background = "#E1E1E3"
foreground = "#323437"

[colors.normal]
black   = "#E1E1E3"
red     = "#DA3333"
green   = "#6A9440"
yellow  = "#C8A010"
blue    = "#5A88B8"
magenta = "#9070A8"
cyan    = "#4A8888"
white   = "#8A8E93"

[colors.bright]
black   = "#8A8E93"
red     = "#DA3333"
green   = "#6A9440"
yellow  = "#E2B714"
blue    = "#5A88B8"
magenta = "#9070A8"
cyan    = "#4A8888"
white   = "#D1D3D8"
