[colors.primary]
background = "#E1E1E3"
foreground = "#323437"

[colors.cursor]
cursor = "#E2B714"
text   = "#323437"

[colors.normal]
black   = "#E1E1E3"
red     = "#DA3333"
green   = "#AAAEB3"
yellow  = "#C8A010"
blue    = "#6A7890"
magenta = "#886888"
cyan    = "#508080"
white   = "#AAAEB3"

[colors.bright]
black   = "#AAAEB3"
red     = "#DA3333"
green   = "#AAAEB3"
yellow  = "#E2B714"
blue    = "#6A7890"
magenta = "#886888"
cyan    = "#508080"
white   = "#D1D3D8"
