[colors.primary]
background = "#323437"
foreground = "#D1D0C5"

[colors.cursor]
cursor = "#E2B714"
text   = "#323437"

[colors.normal]
black   = "#323437"
red     = "#CA4754"
green   = "#8A8E93"
yellow  = "#E2B714"
blue    = "#7888A8"
magenta = "#A07898"
cyan    = "#608888"
white   = "#8A8E93"

[colors.bright]
black   = "#4A4D52"
red     = "#CA4754"
green   = "#8A8E93"
yellow  = "#E2B714"
blue    = "#7888A8"
magenta = "#A07898"
cyan    = "#608888"
white   = "#D1D0C5"
