hl.exec_once("waybar")
hl.exec_once("dunst")
hl.exec_once("nm-applet --indicator")
hl.exec_once("blueman-applet")
hl.exec_once("systemctl --user start hyprpolkitagent")
hl.exec_once("wl-paste --type text  --watch cliphist store")
hl.exec_once("wl-paste --type image --watch cliphist store")
hl.exec_once("swww-daemon")
hl.exec_once("hypridle")
hl.exec_once("sh -c 'sleep 1 && swww img ~/.config/swww/wallpapers/current.png || true'")
