-- Paperlike / e-ink vibe: hairline borders, no shadow, minimal rounding, no blur.
hl.keyword("general:border_size",         "1")
hl.keyword("general:gaps_in",             "4")
hl.keyword("general:gaps_out",            "8")
hl.keyword("general:layout",              "dwindle")
hl.keyword("general:allow_tearing",       "false")
hl.keyword("general:resize_on_border",    "true")

hl.keyword("decoration:rounding",         "2")
hl.keyword("decoration:active_opacity",   "1.0")
hl.keyword("decoration:inactive_opacity", "1.0")
hl.keyword("decoration:blur:enabled",     "false")
hl.keyword("decoration:shadow:enabled",   "false")

hl.keyword("animations:enabled",          "true")
hl.keyword("animations:bezier",           "paper, 0.25, 0.1, 0.25, 1.0")
hl.keyword("animations:animation",        "windows, 1, 3, paper")
hl.keyword("animations:animation",        "border,  1, 6, paper")
hl.keyword("animations:animation",        "fade,    1, 3, paper")
hl.keyword("animations:animation",        "workspaces, 1, 4, paper, slide")

hl.keyword("dwindle:pseudotile",          "true")
hl.keyword("dwindle:preserve_split",      "true")
hl.keyword("misc:disable_hyprland_logo",  "true")
hl.keyword("misc:disable_splash_rendering", "true")
hl.keyword("misc:focus_on_activate",      "true")
hl.keyword("misc:vfr",                    "true")
