[urgency_low]
    background = "#CCCCCC"
    foreground = "#474747"
    frame_color = "#B8B8B8"
[urgency_normal]
    background = "#CCCCCC"
    foreground = "#474747"
    frame_color = "#6B9AB8"
[urgency_critical]
    background = "#CCCCCC"
    foreground = "#C4607A"
    frame_color = "#C4607A"
