[urgency_low]
    background = "#E0DBD3"
    foreground = "#58534C"
    frame_color = "#C8C3BB"
[urgency_normal]
    background = "#E0DBD3"
    foreground = "#58534C"
    frame_color = "#6B9AB8"
[urgency_critical]
    background = "#E0DBD3"
    foreground = "#C4607A"
    frame_color = "#C4607A"
