[urgency_low]
    background = "#E8E8E8"
    foreground = "#1E1E1E"
    frame_color = "#CDCDCD"
[urgency_normal]
    background = "#E8E8E8"
    foreground = "#1E1E1E"
    frame_color = "#3C3C3C"
[urgency_critical]
    background = "#E8E8E8"
    foreground = "#1E1E1E"
    frame_color = "#1E1E1E"
