[urgency_low]
    background = "#323437"
    foreground = "#D1D0C5"
    frame_color = "#2C2E31"
[urgency_normal]
    background = "#323437"
    foreground = "#D1D0C5"
    frame_color = "#E2B714"
[urgency_critical]
    background = "#323437"
    foreground = "#CA4754"
    frame_color = "#CA4754"
