[urgency_low]
    background = "#E1E1E3"
    foreground = "#323437"
    frame_color = "#D1D3D8"
[urgency_normal]
    background = "#E1E1E3"
    foreground = "#323437"
    frame_color = "#E2B714"
[urgency_critical]
    background = "#E1E1E3"
    foreground = "#DA3333"
    frame_color = "#DA3333"
