# vim:ft=kitty

foreground #2C2926
background #F2EDE8
selection_foreground none
selection_background #E5E1DA

cursor #3E3B36
cursor_text_color #2C2926

color0  #F2EDE8
color8  #C8C4BE

color1  #3E3B36
color9  #3E3B36

color2  #5A5652
color10 #686461

color3  #7A7672
color11 #9C9892

color4  #504D49
color12 #504D49

color5  #686461
color13 #7A7672

color6  #9C9892
color14 #AFABA5

color7  #AFABA5
color15 #E5E1DA
