# vim:ft=kitty

foreground #474747
background #CCCCCC
selection_foreground none
selection_background #B8B8B8

cursor none

# black
color0  #CCCCCC
color8  #5E5E5E

# red / error
color1  #C4607A
color9  #C4607A

# green / success
color2  #8BAD79
color10 #8BAD79

# yellow / warning
color3  #B89868
color11 #B89868

# blue / primary accent
color4  #6B9AB8
color12 #6B9AB8

# magenta / dark
color5  #474747
color13 #474747

# cyan
color6  #4A4A4A
color14 #4A4A4A

# white
color7  #5E5E5E
color15 #7C7C7C
