# vim:ft=kitty

foreground #474747
background #CCCCCC
selection_foreground none
selection_background #C2C2C2

cursor #6B9AB8
cursor_text_color #474747

color0  #CCCCCC
color8  #5E5E5E

color1  #C4607A
color9  #C4607A

color2  #8BAD79
color10 #8BAD79

color3  #B89868
color11 #B89868

color4  #6B9AB8
color12 #6B9AB8

color5  #474747
color13 #474747

color6  #4A4A4A
color14 #4A4A4A

color7  #5E5E5E
color15 #7C7C7C
