# vim:ft=kitty

foreground #58534C
background #E0DBD3
selection_foreground none
selection_background #D8D3CB

cursor #6B9AB8
cursor_text_color #58534C

color0  #E0DBD3
color8  #615C56

color1  #C4607A
color9  #C4607A

color2  #8BAD79
color10 #8BAD79

color3  #B89868
color11 #B89868

color4  #6B9AB8
color12 #6B9AB8

color5  #58534C
color13 #58534C

color6  #4E4A45
color14 #4E4A45

color7  #615C56
color15 #7A756E
